### ISSUE TITLE
RateIt moved to GitHub

### ISSUE THREAD

**Issue by gjunge** [AlexanderFedorenko/jquery.rateit#1]
Hi,

The official rateit plugin moved to GitHub: https://github.com/gjunge/rateit.js  

Would it be possible to move the jquery.rateit bower package you've created (thank you for that!), to the new https://github.com/gjunge/rateit.js location (I added a bower.json file).  
This way the endusers will always be pointed to the latest version of rateit.

Thanks!
Gidon

**Comment by AlexanderFedorenko** [comment]
Sure, sorry for delay

**Comment by AlexanderFedorenko** [comment]
So, I unregistered package, now you are free to add your own as an owner.

And thank you for great plugin.

**Comment by gjunge** [comment]
Thanks!
